# Generated by Django 4.0.6 on 2023-01-17 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='pub_date',
            new_name='date',
        ),
    ]
